### ISSUE TITLE
Support IE9

### ISSUE THREAD

**Issue by ricardosimoes** [sunpietro/dragster#17]
I started using this plugin and noticed that on IE9 it doesn't work, the drag item just doesn't drag. Is it normal? Doesn't this plugin give support for IE9 at all?

Thanks

**Comment by sunpietro** [comment]
@ricardosimoes The library was not tested with IE9. I'll update the library documentation with information about supported browsers.

**Comment by ricardosimoes** [comment]
Thanks for the quick answer. :)

Are you thinking about giving support for IE9?

**Comment by sunpietro** [comment]
I'm not sure, as I don't have any access to IE9 browser now. I'll have to do some investigation on this topic.

**Comment by ricardosimoes** [comment]
Thanks, I'll be checking this issue for updates. :)

**Comment by sunpietro** [comment]
@ricardosimoes after investigating the issue, to make Dragster.js library working on IE9 you have to attach the JS classList API polyfill from there: https://github.com/remy/polyfills/blob/master/classList.js
When you add the file to your website/app then it will start working as expected :)
I hope it helps.

**Comment by ricardosimoes** [comment]
It worked! :D Thanks
