### ISSUE TITLE
Scrolling after dragging item on mobile

### ISSUE THREAD

**Issue by ricardosimoes** [sunpietro/dragster#18]
Hi, on mobile when I drag one element to another place and then i try to scroll the page it doesn't scroll. From the tests I made it also happens on the demo page. Do you have any idea why this happens?

**Comment by sunpietro** [comment]
@ricardosimoes can you tell me which mobile devices and which mobile browser were used?

**Comment by ricardosimoes** [comment]
I think that it's not specific to a mobile device or browser. But I tested in a Samsung Galaxy S4 (android browser), iPhone 5s (chrome) and after this failed I also tested on Chrome browser in a desktop using the "Device tool" in the "Inspect" of DevTools (tested iPhone 4). In the desktop the scroll wheel still functioned but the drag didn't.

**Comment by sunpietro** [comment]
@ricardosimoes thanks for reporting. I'll try to investigate it soon.

**Comment by sunpietro** [comment]
@ricardosimoes sorry for not responding for long time. I've added a scroll functionality to *Dragster.js* in the latest version. I've introduced a new property to *Dragster.js* object - `scrollWindowOnDrag` that takes boolean values. By default it's set to `false`.
