### ISSUE TITLE
Dragable Selector Function

### ISSUE THREAD

**Issue by oteroweb** [sunpietro/dragster#38]
There are parameter to set a child element from a dragster-block, for example fa fa-arrows icon

**Comment by sunpietro** [comment]
hi @oteroweb I'm not sure what you mean. Can you elaborate more about the issue?

**Comment by oteroweb** [comment]
like Dragula in moves parameters https://bevacqua.github.io/dragula/

**Comment by sunpietro** [comment]
@oteroweb I see it now. It might a kind of useful functionality to implement.
