### ISSUE TITLE
wrapDraggableElements: false not working + fix

### ISSUE THREAD

**Issue by nevf** [sunpietro/dragster#43]
If I set ```wrapDraggableElements: false``` and add ```draggable="true" class="dragster-draggable"``` to the elementSelector element ```isDraggableCallback()``` returns false because ```element.dataset.dragsterId``` is not set. 

It appears to me as this has replaced the ```draggable="true"``` attribute at some point as I can't see that, that is used.

Setting ```dragsterId``` inside ```wrapDraggableElements()``` as follows fixes this.
````
    wrapDraggableElements = function (elements) {
        if (finalParams.wrapDraggableElements === FALSE) {
            elements.forEach(function (draggableElement) {
                draggableElement.dataset.dragsterId = dragsterId;
            })
       ...
````

**Comment by sunpietro** [comment]
The thing is that `draggable="true"` adds a native drag behaviour, while the `element.dataset.dragsterId` is generated automatically by the script and I'm relying on it internally.
If you set `wrapDraggableElements: false` then it's up to you, to implement the right attributes on elements. I'm not sure that this is a bug (it was made intentionally in #27).
