### ISSUE TITLE
Cannot find module 'dragster.es6.js'

### ISSUE THREAD

**Issue by George35mk** [sunpietro/dragster#44]
Hi, I m trying to use Dragster on typescript project, but I cant import your lib.

```typescript
import * as Dragster from 'dragster.es6.js';

```

I get this on the console
> Cannot find module 'dragster.es6.js'

**Comment by sunpietro** [comment]
@George35mk did it help you?

**Comment by George35mk** [comment]
@sunpietro I want to use your module on Angular 6 project but I can't.

Can you make a typescript version for this?
I work for a scientific research project & the only lib that look great is your but unfortunately, I can't use it.

**Comment by George35mk** [comment]
@HectorLS 
I have tried your solution but not seem to work.
